import type { TocHeading } from "@/components/article/TableOfContents";
/**
 * Extract heading elements from the rendered article DOM.
 *
 * This runs after the MDX renderer has compiled and rendered the body,
 * so heading IDs are already present (generated by rehype-slug). This
 * avoids brittle client-side parsing of raw MDX.
 */
export function extractHeadings(container: HTMLElement | null): TocHeading[] {
  if (!container) return [];
  const headings = container.querySelectorAll("h2, h3, h4");
  const result: TocHeading[] = [];
  headings.forEach((el) => {
    const id = el.id;
    const text = el.textContent?.trim() ?? "";
    if (!id || !text) return;
    const level = parseInt(el.tagName.substring(1), 10);
    result.push({ id, text, level });
  });
  return result;
}