import type { ComponentType } from "react";
import type { Author, Category, Post, PostSummary, Tag } from "./types";
import type { ContentSource, ListPostsOptions } from "./source";
import type { Frontmatter } from "./schema";
import {
  splitFrontmatter,
  validateFrontmatter,
  toSummary,
  toPost,
  deriveStatus,
  categoryName,
  tagName,
} from "./frontmatter";
import { slugFromPath } from "./git/paths";
import { ContentParseError } from "./errors";
// --- Build-time content discovery via Vite raw imports ---------------------
//
// Raw string imports are used for frontmatter parsing (which always needs the
// raw text). The MDX body is compiled at build time by scripts/precompile-mdx
// and the compiled modules are imported lazily by MdxRenderer. In development,
// the precompile script may not have run, so MdxRenderer falls back to runtime
// compilation via Blob URLs (requires `blob:` in CSP for dev only).
/** Map of post slug -> raw file content. */
const postFiles = import.meta.glob<string>("/content/posts/*.{mdx,md}", {
  query: "?raw",
  import: "default",
  eager: true,
});
/** Map of author slug -> raw file content. */
const authorFiles = import.meta.glob<string>("/content/authors/*.{mdx,md}", {
  query: "?raw",
  import: "default",
  eager: true,
});
/**
 * Pre-compiled MDX modules — generated by `scripts/precompile-mdx/script.ts`
 * during the prebuild step. Each module exports a default React component.
 *
 * In development, these may not exist (the prebuild script hasn't run), so
 * MdxRenderer falls back to runtime compilation.
 */
export const compiledPostModules = import.meta.glob<{
  default: ComponentType<{ components?: Record<string, unknown> }>;
}>("/src/lib/content/__compiled__/**/*.js", {
  eager: true,
});
/**
 * Look up a pre-compiled MDX module for a given post slug.
 * Returns null if no compiled module exists (e.g., in development before
 * the prebuild script has run).
 */
export function getCompiledPostModule(slug: string): ComponentType<{
  components?: Record<string, unknown>;
}> | null {
  const key = Object.keys(compiledPostModules).find((k) => k.endsWith(`/${slug}.js`));
  if (!key) return null;
  return compiledPostModules[key]?.default ?? null;
}
/**
 * Local content source adapter.
 *
 * Uses Vite's `import.meta.glob` with `?raw` imports to discover MDX/MD files
 * at build time and parse them at runtime. This keeps the content pipeline
 * filesystem-agnostic: the adapter reads raw strings, parses frontmatter,
 * validates it, and returns typed objects.
 *
 * A remote adapter (GitHub, etc.) can implement the same `ContentSource`
 * interface without touching rendering code.
 */
interface LoadedPost {
  slug: string;
  frontmatter: Frontmatter;
  body: string;
}
/** Cache of parsed posts. */
let postCache: LoadedPost[] | null = null;
/** Load and validate all posts from discovered files. */
function loadAllPosts(): LoadedPost[] {
  if (postCache) return postCache;
  const posts: LoadedPost[] = [];
  const seenSlugs = new Set<string>();
  for (const [filePath, rawContent] of Object.entries(postFiles)) {
    const slug = slugFromPath(filePath);
    let parsed: { frontmatter: Record<string, unknown>; body: string };
    try {
      const content = typeof rawContent === "string" ? rawContent : String(rawContent ?? "");
      parsed = splitFrontmatter(content);
    } catch (err) {
      if (err instanceof ContentParseError) {
        console.error(`[content] Failed to parse post file: ${filePath}`, err);
        continue;
      }
      console.error(`[content] Unexpected error parsing post ${filePath}:`, err);
      continue;
    }
    // Validate frontmatter against schema — skip invalid files gracefully
    // instead of crashing the entire post loader.
    let frontmatter: Frontmatter;
    try {
      frontmatter = validateFrontmatter(parsed.frontmatter, slug, filePath);
    } catch (validationErr) {
      console.warn(
        `[content] Skipping post with invalid frontmatter: ${filePath}`,
        validationErr instanceof Error ? validationErr.message : validationErr,
      );
      continue;
    }
    // Check for duplicate slugs.
    if (seenSlugs.has(slug)) {
      console.warn(`[content] Duplicate post slug "${slug}" found at ${filePath}, skipping.`);
      continue;
    }
    seenSlugs.add(slug);
    posts.push({ slug, frontmatter, body: parsed.body });
  }
  postCache = posts;
  return posts;
}
/** Filter posts by publishing options. */
function filterPosts(posts: PostSummary[], options?: ListPostsOptions): PostSummary[] {
  let result = posts;
  if (!options?.includeUnpublished) {
    result = result.filter((p) => p.status === "published");
  }
  if (options?.status) {
    result = result.filter((p) => p.status === options.status);
  }
  if (options?.featuredOnly) {
    result = result.filter((p) => p.featured);
  }
  const targetLocale = options?.locale;
  if (targetLocale && targetLocale !== "all") {
    result = result.filter((p) => (p.locale || "en") === targetLocale);
  } else if (!targetLocale) {
    // Default to "en" if locale is not provided
    result = result.filter((p) => (p.locale || "en") === "en");
  }
  // Sort by date descending.
  result = [...result].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  return result;
}
// --- Author loading --------------------------------------------------------
let authorCache: Author[] | null = null;
function loadAllAuthors(): Author[] {
  if (authorCache) return authorCache;
  const authors: Author[] = [];
  for (const [filePath, rawContent] of Object.entries(authorFiles)) {
    const slug = slugFromPath(filePath);
    let parsed: { frontmatter: Record<string, unknown>; body: string };
    try {
      const content = typeof rawContent === "string" ? rawContent : String(rawContent ?? "");
      parsed = splitFrontmatter(content);
    } catch (err) {
      if (err instanceof ContentParseError) {
        console.error(`[content] Failed to parse author file: ${filePath}`, err);
        continue;
      }
      console.error(`[content] Unexpected error parsing author ${filePath}:`, err);
      continue;
    }
    const fm = parsed.frontmatter as Record<string, unknown>;
    const socialRaw = (fm.social ?? {}) as Record<string, unknown>;
    authors.push({
      slug,
      name: String(fm.name ?? ""),
      bio: String(fm.bio ?? ""),
      avatar: String(fm.avatar ?? "/placeholder.svg"),
      role: String(fm.role ?? ""),
      social: {
        twitter: typeof socialRaw.twitter === "string" ? socialRaw.twitter : undefined,
        github: typeof socialRaw.github === "string" ? socialRaw.github : undefined,
        linkedin: typeof socialRaw.linkedin === "string" ? socialRaw.linkedin : undefined,
        website: typeof socialRaw.website === "string" ? socialRaw.website : undefined,
      },
    });
  }
  authorCache = authors;
  return authors;
}
// --- LocalSource implementation --------------------------------------------
export const localSource: ContentSource = {
  async listPosts(options?: ListPostsOptions): Promise<PostSummary[]> {
    const posts = loadAllPosts().map((p) => toSummary(p.slug, p.frontmatter, p.body));
    return filterPosts(posts, options);
  },
  async getPostBySlug(slug: string): Promise<Post | null> {
    const posts = loadAllPosts();
    const found = posts.find((p) => p.slug === slug);
    if (!found) return null;
    // Return the post even if unpublished/future-dated — the article page
    // will render a "Coming Soon" state for drafts instead of a 404.
    return toPost(found.slug, found.frontmatter, found.body);
  },
  async getAllCategories(): Promise<Category[]> {
    const posts = loadAllPosts().filter((p) => p.frontmatter.published);
    const slugs = new Set(posts.map((p) => p.frontmatter.category));
    return Array.from(slugs).map((slug) => ({
      slug,
      name: categoryName(slug),
    }));
  },
  async getAllTags(): Promise<Tag[]> {
    const posts = loadAllPosts().filter((p) => p.frontmatter.published);
    const counts = new Map<string, number>();
    for (const post of posts) {
      for (const tag of post.frontmatter.tags) {
        counts.set(tag, (counts.get(tag) ?? 0) + 1);
      }
    }
    return Array.from(counts.entries())
      .map(([slug, count]) => ({ slug, name: tagName(slug), count }))
      .sort((a, b) => b.count - a.count);
  },
  async getPostsByCategory(category: string, options?: ListPostsOptions): Promise<PostSummary[]> {
    const posts = loadAllPosts()
      .filter((p) => p.frontmatter.published && p.frontmatter.category === category)
      .map((p) => toSummary(p.slug, p.frontmatter, p.body));
    return filterPosts(posts, options);
  },
  async getPostsByTag(tag: string, options?: ListPostsOptions): Promise<PostSummary[]> {
    const posts = loadAllPosts()
      .filter((p) => p.frontmatter.published && p.frontmatter.tags.includes(tag))
      .map((p) => toSummary(p.slug, p.frontmatter, p.body));
    return filterPosts(posts, options);
  },
  async getAuthor(slug: string): Promise<Author | null> {
    const authors = loadAllAuthors();
    return authors.find((a) => a.slug === slug) ?? null;
  },
  async getAllAuthors(): Promise<Author[]> {
    return loadAllAuthors();
  },
  async getPostsByTranslationKey(translationKey: string): Promise<PostSummary[]> {
    const posts = loadAllPosts()
      .map((p) => toSummary(p.slug, p.frontmatter, p.body))
      .filter((p) => p.published && p.translationKey === translationKey);
    return filterPosts(posts, { locale: "all" });
  },
};
// Check if a post slug is published and not future-dated.
export function isSlugPublished(slug: string): boolean {
  const posts = loadAllPosts();
  const found = posts.find((p) => p.slug === slug);
  if (!found) return false;
  return deriveStatus(found.frontmatter) === "published";
}

// Re-export for backward compatibility (deriveStatus used by tests).
export { deriveStatus };