import type { ComponentProps, ReactElement } from "react";
import { Link } from "react-router-dom";
import { isSlugPublished } from "@/lib/content";
import Callout from "./Callout";
import Note from "./Note";
import Warning from "./Warning";
import CodeBlock from "./CodeBlock";
import InlineCode from "./InlineCode";
import ResponsiveImage from "./ResponsiveImage";
import ExternalLink from "./ExternalLink";
import ArticleTable from "./ArticleTable";
import Quote from "./Quote";
import ComparisonTable from "./ComparisonTable";
import ChecklistBox from "./ChecklistBox";
import CTACard from "./CTACard";
import { AccordionGroup, AccordionItem } from "./AccordionGroup";
import { TabsGroup, TabsList, TabsTrigger, TabsContent } from "./TabsGroup";
import VideoEmbed from "./VideoEmbed";
import ImageZoom from "./ImageZoom";
import SponsoredBadge from "./SponsoredBadge";
import SheetMusicExcerpt from "./SheetMusicExcerpt";
import PianoKeyboard from "./PianoKeyboard";
import PracticeExercise from "./PracticeExercise";
/**
 * Centralized MDX component registry.
 *
 * Only the components listed here are available to MDX authors. This is the
 * security boundary: no arbitrary imports or user-provided JavaScript can
 * reach the rendered output. MDX is treated as trusted executable content,
 * but the component surface is explicitly controlled.
 *
 * GitHub-flavored Markdown (tables, strikethrough, task lists, autolinks) is
 * handled by remark-gfm in the renderer. Heading IDs are generated by
 * rehype-slug. Syntax highlighting is applied by rehype-highlight.
 */
/** Check whether a URL is an internal (same-site) link. */
function isInternal(href: string): boolean {
  return (
    href.startsWith("/") ||
    href.startsWith("#") ||
    href.startsWith("?") ||
    (!href.startsWith("http://") && !href.startsWith("https://") && !href.startsWith("mailto:"))
  );
}
function extractArticleSlug(href: string): string | null {
  const match = href.match(/^\/(?:articles|blog)\/([^/#?]+)/);
  return match ? match[1] : null;
}

/** Anchor element: routes internal links through react-router, external links open in a new tab. */
const Anchor = ({
  href = "",
  children,
  title,
  // Allow MDX authors to pass sponsored/nofollow via custom props
  ...rest
}: ComponentProps<"a"> & { sponsored?: boolean; nofollow?: boolean }): ReactElement => {
  if (isInternal(href)) {
    const articleSlug = extractArticleSlug(href);
    if (articleSlug && !isSlugPublished(articleSlug)) {
      // Drip unlinking: prevent broken/early links to scheduled or unpublished articles
      return <span className="text-foreground/90 font-normal">{children}</span>;
    }

    // Hash links within the same page should use a plain <a> so the browser
    // handles scroll; everything else goes through the router.
    if (href.startsWith("#") || href.startsWith("?")) {
      return (
        <a
          href={href}
          title={title}
          className="text-primary underline underline-offset-2 hover:opacity-80"
        >
          {children}
        </a>
      );
    }
    return (
      <Link to={href} className="text-primary underline underline-offset-2 hover:opacity-80">
        {children}
      </Link>
    );
  }
  return (
    <ExternalLink href={href} title={title} sponsored={rest.sponsored} nofollow={rest.nofollow}>
      {children}
    </ExternalLink>
  );
};
type HeadingTag = "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
/** Heading wrapper that adds an anchor link to each heading's slug (generated by rehype-slug). */
function withAnchorLink(Tag: HeadingTag) {
  const Wrapped = ({ id, children, ...rest }: ComponentProps<"h1">) => (
    <Tag id={id} className="group scroll-mt-20" {...rest}>
      {children}
      {id ? (
        <a
          href={`#${id}`}
          aria-label={`Permalink to section: ${typeof children === "string" ? children : "this section"}`}
          className="ml-2 text-muted-foreground/40 opacity-0 transition-opacity group-hover:opacity-100 focus-visible:opacity-100 focus-visible:outline-2 focus-visible:outline-offset-2"
        >
          #
        </a>
      ) : null}
    </Tag>
  );
  Wrapped.displayName = Tag.toUpperCase();
  return Wrapped;
}
/**
 * The MDX component map. Passed to the MDX runtime as the `components` prop.
 * Every HTML element that MDX can render is mapped here so we control the
 * exact output and styling.
 */
export const mdxComponents = {
  // h1 is intentionally omitted — the article's H1 is rendered by ArticleHeader.
  // MDX body content should start at h2.
  h2: withAnchorLink("h2"),
  h3: withAnchorLink("h3"),
  h4: withAnchorLink("h4"),
  h5: withAnchorLink("h5"),
  h6: withAnchorLink("h6"),
  p: ({ children, ...rest }: ComponentProps<"p">) => (
    <p className="mb-4 text-lg leading-relaxed" {...rest}>
      {children}
    </p>
  ),
  a: Anchor,
  ul: ({ children, ...rest }: ComponentProps<"ul">) => (
    <ul className="mb-4 list-disc space-y-1 pl-6" {...rest}>
      {children}
    </ul>
  ),
  ol: ({ children, ...rest }: ComponentProps<"ol">) => (
    <ol className="mb-4 list-decimal space-y-1 pl-6" {...rest}>
      {children}
    </ol>
  ),
  li: ({ children, ...rest }: ComponentProps<"li">) => (
    <li className="text-lg leading-relaxed" {...rest}>
      {children}
    </li>
  ),
  blockquote: ({ children, cite }: ComponentProps<"blockquote">) => (
    <Quote cite={cite as string | undefined}>{children}</Quote>
  ),
  pre: ({ children }: ComponentProps<"pre">) => <CodeBlock>{children}</CodeBlock>,
  code: ({ children, className }: ComponentProps<"code">) => {
    // Inline code (no language class) uses InlineCode; fenced code is handled
    // by the <pre> -> CodeBlock wrapper and the highlight.js classes.
    // rehype-highlight adds "hljs language-xxx" to fenced code blocks.
    if (className && className.includes("language-")) {
      return <code className={className}>{children}</code>;
    }
    return <InlineCode>{children}</InlineCode>;
  },
  table: ({ children }: ComponentProps<"table">) => <ArticleTable>{children}</ArticleTable>,
  thead: ({ children, ...rest }: ComponentProps<"thead">) => (
    <thead className="border-b border-border bg-muted/40" {...rest}>
      {children}
    </thead>
  ),
  th: ({ children, ...rest }: ComponentProps<"th">) => (
    <th className="border-b border-border px-4 py-2 text-left font-semibold" {...rest}>
      {children}
    </th>
  ),
  td: ({ children, ...rest }: ComponentProps<"td">) => (
    <td className="border-b border-border px-4 py-2" {...rest}>
      {children}
    </td>
  ),
  hr: () => <hr className="my-8 border-border" />,
  img: ({ src, alt, width, height }: ComponentProps<"img">) => (
    <ResponsiveImage
      src={src ?? ""}
      alt={alt ?? ""}
      width={typeof width === "string" ? parseInt(width, 10) : width}
      height={typeof height === "string" ? parseInt(height, 10) : height}
    />
  ),
  // Explicitly registered custom components available to MDX authors.
  Callout,
  Note,
  Warning,
  Quote,
  ResponsiveImage,
  ExternalLink,
  ComparisonTable,
  ChecklistBox,
  CTACard,
  // --- Rich interactive components ---
  AccordionGroup,
  AccordionItem,
  TabsGroup,
  TabsList,
  TabsTrigger,
  TabsContent,
  VideoEmbed,
  ImageZoom,
  SponsoredBadge,
  // --- PianoEd domain-specific components ---
  SheetMusicExcerpt,
  PianoKeyboard,
  PracticeExercise,
};
export type MdxComponents = typeof mdxComponents;